name: Daily House Data Update

on:
  push:
    paths:
      - 'house_scripts/**'
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write

jobs:
  run-daily-jobs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-noto-cjk fonts-noto-cjk-extra
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run daily jobs script
      env:
        BARK_SECRET_KEY: ${{ secrets.BARK_SECRET_KEY }}
        BARK_SECRET_KEY_TINA: ${{ secrets.BARK_SECRET_KEY_TINA }}
      run: |
        cd house_scripts
        python daily_jobs.py
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Update house data and plots" || exit 0
        git push origin HEAD:${GITHUB_REF} --force
      env:
        GITHUB_TOKEN: ${{ github.token }}
